[tool.poetry]
name = "app"
version = "0.1.0"
description = "Main app toml"
authors = ["Nikolay example@example.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.5"
fastapi = "0.105.0"
pika = "1.3.2"
uvicorn = "0.24.0.post1"
SQLAlchemy = "2.0.2"
requests = "^2.31.0"
